services:
  postgres:
    image: postgres:17
    restart: always
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8473:5432"

volumes:
  postgres_data: